#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_DEVICE_INIT_NVIC_PRESENT
#define SL_CATALOG_EMLIB_CORE_PRESENT
#define SL_CATALOG_EMLIB_CORE_DEBUG_CONFIG_PRESENT
#define SL_CATALOG_IOSTREAM_UART_COMMON_PRESENT
#define SL_CATALOG_IOSTREAM_USART_PRESENT
#define SL_CATALOG_PRINTF_PRESENT

#endif // SL_COMPONENT_CATALOG_H
